# Generated by Django 5.2 on 2025-09-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_googlecredential_oauthstate_delete_cancion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='default_calendar_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
