# Generated by Django 5.2 on 2025-09-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_team_default_calendar_id'),
    ]

    operations = [
    ]
