# Generated by Django 5.2 on 2025-11-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_task_completion_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed_by',
        ),
        migrations.AddField(
            model_name='task',
            name='tipo',
            field=models.CharField(choices=[('file_upload', 'Subir Archivo'), ('meeting', 'Reunión Programada'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('done', 'Completada'), ('overdue', 'Retrasada')], default='pending', max_length=20),
        ),
    ]
